### ISSUE TITLE
Will not compile on "up-to-date" main branch of bevy

### ISSUE THREAD

**Issue by Lemiczek** [superdump/bevy-vertex-pulling#1]
Hello!

Right now, if you try to compile and run the examples on the `main` branch `[v0.8.0-dev]` of bevy, a lot of dependencies will be missing or moved. Editing the relevant `Cargo.toml` to a commit made on May 11th in https://github.com/bevyengine/bevy/commit/ae580e58dd1d8539e26a44a4d428e1aa45a3d6f9 solves this "issue". Not ideal as the code might be rendered obsolete in newer bevy revisions, but it would be better than not being able to run the examples at all?
[Last commit](https://github.com/superdump/bevy-vertex-pulling/commit/10b66e857560f56e8387a166ed8fa9368c6d44dd) made on this repo is that of May 11th, which is why I chose the commit made on the same day.
```toml
#Cargo.toml
bevy = { version= "0.8.0-dev",git = "https://github.com/bevyengine/bevy", rev="ae580e5" }
```
```toml
#examples_utils/Cargo.toml
bevy = { version = "0.8.0-dev", git = "https://github.com/bevyengine/bevy", rev="ae580e5" }
```

I can open a pull request and submit the change if need be.

**Comment by superdump** [comment]
I'd rather keep it up to date with bevy main for now. I've fixed it and pushed so it should now work.
